### PR TITLE
Rl changes 2

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
My review is done! Please review suggested changes @eugenividal. We can discuss some of the questions raised. Really enjoyed reading, great paper.

**Review by eugenividal — APPROVED** [review]
Great feedback, Robin! Thanks for taking the time (on a Saturday) to take a look. I really appreciate it. I will merge these changes now. A few thoughts: 1) The introduction and methods are almost done (I'll try to make it clearer why we focus on road lighting and not darkness, I think this is key and explains why we only selected ten papers); 2) The results are also almost done, even so, I will try to extend this section more and write it in a more narrative way (from the initial simple descriptive studies to the latest more sophisticated and precise studies). 3) The discussion and conclusions need more work (I included the 4 questions to make it easier and more pleasant to read, do you like this idea of having 4 questions to answer?). In short, I think we can submit this soon. I do not have much experience with this but it seems to me that if a literature review is rejected it will be more because of the approach or the selected papers than because of the discussion and conclusions, (which are always improvable and easy to do if the reviewers make any comments about it).

**Comment by eugenividal** [comment]
Regarding your first comment, (I think I already told you before) I struggle to understand the difference between 'uptake' and 'levels':
UPTAKE: the action of taking up or making use of something that is available.
LEVELS: a position on a scale of amount, quantity, extent, or quality.
In Spanish (or similarly in Catalan), we usually talk about 'el uso de la bicicleta'. What would be 'uso' for your? UPTAKE, LEVELS, or both?

**Comment by Robinlovelace** [comment]
> In Spanish (or similarly in Catalan), we usually talk about 'el uso de la bicicleta'. What would be 'uso' for your? UPTAKE, LEVELS, or both?

Good question...

**Comment by Robinlovelace** [comment]
"Uptake" means change, basically "cycling uptake" = "increase in cycling"

**Comment by Robinlovelace** [comment]
And "level" just means amount of cycling, I think... Key difference is that uptake implies change over time.

**Comment by eugenividal** [comment]
I know what you mean, but in this context (of associative scientific studies) I see the terms as synonyms. I mean when a study examines the association of 'cycling levels' with any factor, it aims to know how that factor affects cycling (positively or negatively) in order to know how cycling may evolve in time depending on that specific factor. Do you know what I mean?

**Comment by Robinlovelace** [comment]
> would you use a different dependent variable to examine 'cycling uptake' than to examine 'cycling levels'? Do you have an example?

Yes, the dependent variable would be different:

- Uptake example: change in cycling levels between 2001 and 2021, e.g. 2.6%, 3.6%, with 1 percentage point change over that period being the y value to predict.
- Level example: 3.6% is the dependent variable.

On a related note: I would like to research the change in % cycling to work accounting for many factors between 2001, 2011 and 2021. That would be modelling uptake over time. In my court!

**Comment by eugenividal** [comment]
Thanks for the example. I see it clearly now. In that case, given that none of the papers reviewed uses percentage change over a period of time, the title of the review should be 'The effect of road lighting on cycling LEVELS'. Do you agree?

**Pull request merged**
