### PR TITLE
16 response to reviewers

### PR DESCRIPTION
**Pull request by Robinlovelace**
- First go at reviewer 1
- Add responses ideas
- Add section on context

### CODE REVIEW

**Review by eugenividal — APPROVED** [review]
Great tweaks! it sounds more convincing now, thanks Robin!

**Review by eugenividal — APPROVED** [review]
Great general response to the editor. Approved!

**Comment by Robinlovelace** [comment]
Thanks Eugeni, please merge. Greetings from Poland, just arrived at the 'BikeOV Studio' and getting ready for OpenGeoHub.

**Comment by Robinlovelace** [comment]
May be of interest: https://ogh23.robinlovelace.net/

**Review by eugenividal — APPROVED** [review]
The changes in the manuscript look good. Not sure whether I would create a specific section or integrate the ideas into the existing discussion subsections. I'll think about it. Aprove for now. Great tweaks in the response to reviewers.

**Review by eugenividal — COMMENTED** [review]
Not sure about these comments. I think we are getting a bit out of focus. Not sure whether it is worth it to include these new references. @cerin_neighbourhood_2017 does not provide specific evidence that lighting is associated with cycling in particular (otherwise it would be in the table with the rest of the references). I find @xiao_shifting_2022 out of context. Regarding the last consideration to justify our focus, I think our argumentation that walking and cycling are different modes of transport regarding lighting is more than enough. The argument that promoting cycling makes more sense than walking is more arguable. Yes, bikes and e-bikes go further but fewer people are able to cycle. I think the potentiality depended also on the context. In countries like the UK and the US with the urban sprawl urbanism is possible, but in other countries with denser cities walking may have a bigger potential. I'll not approve these changes at the moment but will consider including them or part of them.

**Review by eugenividal — COMMENTED** [review]
I find this a bit out of context. Will consider it together with the previous comments.

**Comment by Robinlovelace** [comment]
Will leave it in your hands, happy for you to incorporate some of these suggestions without merging this. Many thanks and greetings from Poland!

**Comment by eugenividal** [comment]
Hey @Robinlovelace, thanks for your valuable input. Merging the changes I totally agree. I will reread it all again tomorrow to consider your last suggestions. I will keep you updated. Good luck with your presentation tomorrow!

**Pull request merged**
